import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="font-bold text-9xl">Hello</div>
    </div>
  );
};

export default Home;
